Library_/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('', include('home.urls')),
                  path('admin/', admin.site.urls),
                  path('user/', include('users.urls')),
                  path('book/', include('books.urls')),
                  # path('email/', include('sendEmail.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

books/urls.py
from django.urls import path

from books.views import book_list, book_create, kartoteka_create, book_detail, book_category, book_update

app_name = 'books'
urlpatterns = [
    path('list/', book_list, name='book_list'),
    path('create/', book_create, name='book_create'),
    path('kartoteka_create/', kartoteka_create, name='kartoteka_create'),
    path('book_detail/<int:pk>', book_detail, name='book_detail'),
    path('category/<str:category>/', book_category, name='book_category'),
    path('book_update/<int:pk>/', book_update, name='book_update'),
]

home/urls.py
from django.urls import path

from home.views import home

app_name = 'home'

urlpatterns = [
    path('', home, name='home'),
]

users/urls.py
from django.urls import path

from .views import registration, _login, _logout, personal_cabinet, reset_password, verify_user, \
    user_update

app_name = 'users'
urlpatterns = [
    path('registration/', registration, name='registration'),
    path('login/', _login, name='_login'),
    path('logout/', _logout, name='logout'),
    path('personal_cab/', personal_cabinet, name='personal_cabinet'),
    path('reset_password/', reset_password, name='reset_password'),
    path('verify/', verify_user, name='verify_user'),
    path('update_user/', user_update, name='user_update'),
]

users/models.py
import datetime
from os.path import join as join_path

from django.contrib.auth.models import User
from django.db import models


class Abstract(models.Model):
    created_by = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    is_deleted = models.IntegerField(default=0)
    updated_at = models.DateTimeField(null=True, blank=True)
    updated_by = models.IntegerField(null=True, blank=True)

    class Meta:
        abstract = True


class Reader(Abstract):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    picture = models.ImageField(upload_to=join_path('reader', 'picture'))
    profession = models.CharField(max_length=200)
    card = models.IntegerField(null=True, blank=True)
    phone = models.CharField(max_length=12)

    def __str__(self):
        return f'{self.user.get_username()}'


class Employee(Abstract):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    picture = models.ImageField(upload_to=join_path('employee', 'picture'))
    phone = models.CharField(max_length=12)


class Token(models.Model):
    token = models.CharField(max_length=150)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    is_delete = models.IntegerField(default=0)
    send_time = models.DateTimeField()

    def __str__(self):
        return self.token

users/forms.py
from django import forms


class ReaderForm(forms.Form):
    username = forms.CharField(max_length=200)
    first_name = forms.CharField(max_length=200)
    last_name = forms.CharField(max_length=200)
    email = forms.EmailField()
    picture = forms.ImageField()
    phone = forms.CharField(max_length=12)
    profession = forms.CharField(max_length=200)
    card = forms.IntegerField()
    password = forms.CharField(widget=forms.PasswordInput())
    re_password = forms.CharField(widget=forms.PasswordInput())


class EmployeeForm(forms.Form):
    username = forms.CharField(max_length=200)
    first_name = forms.CharField(max_length=200)
    last_name = forms.CharField(max_length=200)
    email = forms.EmailField()
    picture = forms.ImageField()
    phone = forms.CharField(max_length=12)
    password = forms.CharField(widget=forms.PasswordInput())
    re_password = forms.CharField(widget=forms.PasswordInput())

users/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.hashers import make_password
from django.contrib.auth.models import User
from django.core.paginator import Paginator
from django.db import transaction
from django.db.models import Q
from django.http import HttpResponse
from django.shortcuts import render, redirect

from sendEmail.views import send_activation_link
from .forms import ReaderForm, EmployeeForm
from .models import Reader, Token, Employee
from .service.utils import checking_password, checking_employee, user_update_, get_user_


@transaction.atomic
def employee_create(request):
    if request.method == 'POST':
        data = EmployeeForm(request.POST, request.FILES).data
        img = request.FILES.get('picture')
        user = User(username=data.get('username'), first_name=data.get('first_name'),
                    last_name=data.get('last_name'),
                    email=data.get('email'), password=make_password(data.get('password')), is_staff=1)
        user.save()
        Employee(user=user, phone=data.get('phone'), picture=img).save()
        return redirect('books:book_list')
    form = EmployeeForm()
    context = {'form': form}
    return render(request, template_name='registration.html', context=context)


@transaction.atomic
def registration(request):
    if request.method == 'POST':
        data = ReaderForm(request.POST, request.FILES).data
        img = request.FILES.get('picture')
        if checking_password(data.get('password'), data.get('re_password')):
            user = User(username=data.get('username'), first_name=data.get('first_name'),
                        last_name=data.get('last_name'),
                        email=data.get('email'), password=make_password(data.get('password')))
            user.save()
            Reader(user=user, phone=data.get('phone'), picture=img, card=data.get('card'),
                   profession=data.get('profession')).save()
        return redirect('users:_login')
    form = ReaderForm()
    context = {'form': form}
    return render(request, template_name='registration.html', context=context)


def _login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user:
            login(request, user)
            return render(request, template_name='index.html')
        messages.error(request=request, message='Bad credentials')
    return render(request, template_name='login.html', context={})


def _logout(request):
    logout(request)
    return redirect('home:home')


def personal_cabinet(request):
    name = request.GET.get('search', '')

    reader = request.user.reader
    books = reader.kartoteka_set.all()
    if name:
        books = books.filter(Q(book__title__icontains=name) | Q(book__author__icontains=name))
    page = request.GET.get('page', 1)
    pagination = Paginator(books, 3)
    books = pagination.page(page)
    context = {'books': books}
    if request.user.is_staff:
        user = checking_employee(request)
        context = {'books': books, 'user': user}
    return render(request, template_name='personal_cabinet.html', context=context)


def reset_password(request):
    if request.method == 'POST':
        username = request.POST.get('username', '')
        email = request.POST.get('email', '')
        user = User.objects.filter(username=username).first()
        if user.email.__eq__(email):
            send_activation_link(user)
            return render(request, template_name='reset_dane.html', context={'have': True})
        return render(request, template_name='reset_dane.html', context={'have': False})
    return render(request, template_name='reset_password.html')


def verify_user(request):
    token = request.GET.get('token')
    _token = Token.objects.get(token=token, is_delete=0)
    if _token:
        user = _token.user
        return new_password_page(request, user)
    return HttpResponse('This token is invalid')


def new_password_page(request, user):
    if request.method == 'POST':
        new_password(username=user.username, password=request.POST.get('password', ''))
        return redirect('users:_login')
    return render(request, template_name='new_password.html')


def new_password(username, password):
    user = User.objects.filter(username=username)
    user.update(password=make_password(password))


def user_update(request):
    form = get_user_(request.user.pk)
    if request.method == 'POST':
        user_update_(request, request.user.pk)
        return redirect('users:personal_cabinet')
    return render(request, template_name='update_user.html', context=form)

users/templates/login.html
{% extends 'base.html' %}
{% block title %}
    Login
{% endblock title %}
{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        {#        <div class="alert">#}
        {#            <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>#}
        {#            {% if messages %}#}
        {#                {% for message in messages %}#}
        {#                    {{ message }}#}
        {#                {% endfor %}#}
        {#            {% endif %}<br>#}
        {#        </div>#}
        <table>
            <label for=""></label>
            username <input type="text" name="username" placeholder="username" class="m-2"><br/>
            password <input type="password" name="password" class="m-2">
        </table>
        <a href="{% url 'users:reset_password' %}">Reset Password</a><br>
        <a href="{% url 'users:registration' %}" class="btn btn-primary m-2">Registration</a>
        <input type="submit" class="btn btn-success m-2" name="login" value="login">
    </form>
{% endblock content %}

users/templates/logout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

users/templates/new_password.html
{% extends 'base.html' %}
{% block title %}
    New password
{% endblock title %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        <input type="password" name="password" placeholder="password"><br>
        <input type="password" name="re_password" placeholder="re_password"><br>
        <input type="submit" name="save" value="save"><br>
    </form>
{% endblock content %}

users/templates/personal_cabinet.html
{% extends 'base.html' %}
{% block title %}
    Personal Cabinet
{% endblock title %}
{% block content %}
    {% if user.is_staff %}
        <h1>{{ user }}</h1>
    {% endif %}
    {% if books %}
        <ol>
            {% for book in books %}
                <div class="m-3">
                    <li>
                        {{ book.book.title }}
                    </li>
                    <li class="mt-3">
                        <img src="{{ book.book.picture.url }}" alt="" class="book_pic">
                    </li>
                </div>
            {% endfor %}
        </ol>
    {% endif %}

    {% if books.has_previous %}
        <a href="?page={{ books.previous_page_number }}" class="btn btn-primary">Previous</a>
    {% endif %}

    {% for page in books.paginator.page_range %}
        {% if books.number == page %}
            <a href="?page={{ page }}" class="btn btn-success">{{ page }}</a>
        {% else %}
            <a href="?page={{ page }}" class="btn btn-info">{{ page }}</a>
        {% endif %}

    {% endfor %}


    {% if books.has_next %}
        <a href="?page={{ books.next_page_number }}" class="btn btn-primary">Next</a>

    {% endif %}
    {#    <div class="mt-2">#}
    {#        <a href="{% url 'books:book_list' %}" class="btn btn-primary">Back</a>#}
    {#    </div>#}
{% endblock content %}

users/templates/reader_create.html
{% extends 'base.html' %}
{% block title %}
    Create reader
{% endblock title %}

{% block content %}
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <table>
            <tr>
                {{ form }}
            </tr>
        </table>
        <input type="submit" name="save" value="save" class="btn btn-success">
    </form>
{% endblock content %}

users/templates/registration.html
{% extends 'base.html' %}
{% block title %}
    Create employee
{% endblock title %}

{% block content %}
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <table>
            <tr>
                {{ form }}
            </tr>
        </table>
        <input type="submit" name="save" value="save" class="btn btn-success">
    </form>
{% endblock content %}

users/templates/reset_dane.html
{% extends 'base.html' %}
{% block title %}
    Reset done
{% endblock title %}
{% block content %}
    {% if  have %}
        <h3>
            We have send activation link to your mail
            <br>
            Please Activate Your account
            <a href="">{{ user.email }}</a>
        </h3>
    {% else %}
        <h3>You have not registered before</h3>
    {% endif %}
{% endblock content %}

users/templates/reset_password.html
{% extends 'base.html' %}
{% block title %}
    Reset password
{% endblock title %}
{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        <input type="text" name="username" placeholder="username" class="m-2"><br>
        <input type="text" name="email" placeholder="user@gmail.com" class="m-2"><br>
        <input type="submit" name="send" value="send" class="m-2"><br>
        <a href="{% url 'users:registration' %}" class="btn btn-success m-2" >Registration</a><br>
    </form>
{% endblock content %}

users/templates/update_user.html
{% extends 'base.html' %}
{% block title %}
    Update user
{% endblock title %}

{% block content %}
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <label for="username"><h4>Username</h4></label>
        <input type="text" name="username" value="{{ username }}"><br>
        <label for="first_name"><h4>First_name</h4></label>
        <input type="text" name="first_name" value="{{ first_name }}"><br>
        <label for="last_name"><h4>Last_name</h4></label>
        <input type="text" name="last_name" value="{{ last_name }}"><br>
        <label for="email"><h4>Email</h4></label>
        <input type="email" name="email" value="{{ email }}"><br>
        <label for="picture"><h4>Picture</h4></label>
        <input type="file" name="picture" value="{{ picture }}"><br>
        {% if not request.user.is_staff %}
            <label for="phone"><h4>Phone</h4></label>
            <input type="number" name="phone" value="{{ phone }}"><br>
            <label for="profession"><h4>Profession</h4></label>
            <input type="text" name="profession" value="{{ profession }}"><br>
            <label for="card"><h4>Card</h4></label>
            <input type="number" name="card" value="{{ card }}"><br>
        {% endif %}
        <label for="password"><h4>Password</h4></label>
        <input type="password" name="password" value="{{ password }}"><br>
        {#        <label for="re_password"><h4>Re_password</h4></label>#}
        {#        <input type="password" name="re_password" value="{{ re_password }}"><br>#}
        <input type="submit" name="save" value="save" class="btn btn-success">
    </form>

{% endblock content %}