Library_/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('', include('home.urls')),
                  path('admin/', admin.site.urls),
                  path('user/', include('users.urls')),
                  path('book/', include('books.urls')),
                  # path('email/', include('sendEmail.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

books/urls.py
from django.urls import path

from books.views import book_list, book_create, kartoteka_create, book_detail, book_category, book_update

app_name = 'books'
urlpatterns = [
    path('list/', book_list, name='book_list'),
    path('create/', book_create, name='book_create'),
    path('kartoteka_create/', kartoteka_create, name='kartoteka_create'),
    path('book_detail/<int:pk>', book_detail, name='book_detail'),
    path('category/<str:category>/', book_category, name='book_category'),
    path('book_update/<int:pk>/', book_update, name='book_update'),
]

home/urls.py
from django.urls import path

from home.views import home

app_name = 'home'

urlpatterns = [
    path('', home, name='home'),
]

books/models.py
import datetime
from os.path import join as join_path

from django.contrib.auth.models import User
from django.db import models

from books.service.utils import BookType
from users.models import Abstract, Reader


class Book(Abstract):
    title = models.CharField(max_length=200)
    picture = models.ImageField(upload_to=join_path('books', 'picture'))
    author = models.CharField(max_length=200)
    category = models.CharField(max_length=200, choices=BookType.choice())
    count = models.IntegerField(default=1)
    cost = models.IntegerField(default=20000)
    read_count = models.IntegerField(default=0)
    stars = models.IntegerField(default=0)
    book_file = models.FileField(upload_to=join_path('books', 'files'), null=True, blank=True)

    def __str__(self):
        return self.title.capitalize()


class Kartoteka(Abstract):
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    reader = models.ForeignKey(Reader, on_delete=models.CASCADE)
    return_date = models.DateTimeField(default=(datetime.datetime.now() + datetime.timedelta(days=15)))

    def __str__(self):
        return f'{self.reader.user.get_username()}<-->{self.book.title}'

books/forms.py
from django import forms
from .models import Book, Kartoteka


class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ['title', 'author', 'picture', 'count', 'category', 'book_file']


class KartotekaForm(forms.ModelForm):
    class Meta:
        model = Kartoteka
        fields = ['reader', 'book', 'return_date']

books/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.paginator import Paginator
from django.db import transaction
from django.db.models import Q
from django.shortcuts import render, redirect
from django.utils import timezone

from .forms import BookForm, KartotekaForm
from .models import Book, Kartoteka
from .service import increment_read_book


def book_list(request):
    books = Book.objects.all()
    name = request.GET.get('search', '')
    if name:
        books = Book.objects.filter(Q(title__icontains=name) | Q(author__icontains=name))
    page = request.GET.get('page', 1)
    pagination = Paginator(books, 3)
    books = pagination.page(page)
    context = {'book_list': books}
    return render(request, 'book_list.html', context=context)


@transaction.atomic
@login_required
def book_create(request):
    current_user = request.user
    if request.method == "POST":
        # form = BookForm(request.POST, request.FILES.get('picture'))
        # book = form.save(commit=False)
        # book.created_by = current_user.id
        # book.created_at = timezone.now()
        # book.book_file = BookForm(request.POST, request.FILES.get('file'))
        form = BookForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('books:book_list')
    form = BookForm()
    context = {'form': form}
    return render(request, template_name='book_create.html', context=context)


@transaction.atomic
@login_required
def kartoteka_create(request):
    current_user = request.user
    if request.method == "POST":
        form = KartotekaForm(request.POST, request.FILES)
        kartoteka = form.save(commit=False)
        kartoteka.created_by = current_user.id
        kartoteka.created_at = timezone.now()
        kartoteka.save()
        return redirect('books:book_list')
    form = KartotekaForm()
    context = {'form': form}
    return render(request, template_name='kartoteka_create.html', context=context)


def book_detail(request, pk):
    book = Book.objects.filter(pk=pk).first()
    context = {'book': book}
    user = User.objects.filter(pk=request.user.id).first()
    if request.method == 'POST':
        if user and not user.is_anonymous and not user.is_staff:
            reader = user.reader
            Kartoteka(book=book, reader=reader, created_at=timezone.now(), created_by=reader.user.id).save()
            return redirect('books:book_list')
        else:
            return redirect('users:_login')
    increment_read_book(book_id=pk)
    return render(request, template_name='book_detail.html', context=context)


def book_category(request, category=None):
    if category:
        books = Book.objects.filter(category=category).all()
    else:
        books = Book.objects.all()
    page = request.GET.get('page', 1)
    pagination = Paginator(books, 3)
    books = pagination.page(page)
    context = {'book_list': books}
    return render(request, template_name='book_list.html', context=context)


def book_update(request, pk):
    if request.method == 'POST':
        book = Book.objects.get(pk=pk)
        book.title = request.POST.get('title') or book.title
        book.author = request.POST.get('author') or book.author
        book.picture = request.FILES.get('picture') or book.picture
        book.count = request.POST.get('count') or book.count
        book.cost = request.POST.get('cost') or book.cost
        book.book_file = request.FILES.get('file') or book.book_file
        book.save()
        return redirect('books:book_detail', pk)
    book = Book.objects.filter(pk=pk).first()
    form = {'title': book.title, 'author': book.author, 'picture': book.picture.url, 'count': book.count,
            'cost': book.cost, 'category': book.category, 'file': book.book_file}
    return render(request, template_name='book_update.html', context={'form': form})

books/templates/book_create.html
{% extends 'base.html' %}
{% block title %}
    Create book
{% endblock title %}

{% block content %}
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <table>
            <tr>
                {{ form }}
            </tr>
        </table>
        <input type="submit" value="Save" name="Save" class="btn btn-success">
    </form>
{% endblock content %}

books/templates/book_detail.html
{% extends 'base.html' %}
{% block title %}
    Book detail
{% endblock title %}
{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        <div class="book-card">
            <h3>{{ book.title }}</h3>
            <img src="{{ book.picture.url }}" class="book_pic" alt="{{ book.title }}">
            <h4>author:{{ book.author }}</h4>
            <p>count: {{ book.count }}</p>
            <p>Cost: {{ book.cost }} So'm</p>
            <a href="{{ book.book_file.url }}" download="{{ book.book_file.url }}">Download PDF</a><br/>
        </div>
        <a href="{% url 'books:book_list' %}" class="btn btn-primary">Back</a>
        {% if request.user.is_staff %}
            <a href="{% url 'books:book_update' book.id %}" class="btn btn-secondary m-2">edit</a>
        {% else %}
            <input type="submit" name="add" value="Add card" class="btn btn-secondary">
        {% endif %}

    </form>

{% endblock content %}

books/templates/book_list.html
{% extends 'base.html' %}
{% block title %}
    Books
{% endblock title %}
{% block content %}
    {% if book_list %}
        <ul>
            {% for book in book_list %}
                <div class="m-3 mt-5">
                    <li>
                        <h3><a href="{% url 'books:book_detail' book.id %}">{{ book.title }}</a></h3>
                    </li>
                    <li class="mt-3">
                        {% if book.picture.url.ex %}
                        
                        {% endif %} 
                        <a href="{% url 'books:book_detail' book.id %}">
                            <img src="{{ book.picture.url }}" alt="{{ book.title }}" class="book_pic "></a>
                    </li>
                </div>
            {% endfor %}
        </ul>
    {% else %}
        <h1>Books not found</h1>
    {% endif %}


    {% if book_list.has_previous %}
        <a href="?page={{ book_list.previous_page_number }}" class="btn btn-primary">Previous</a>
    {% endif %}

    {% for page in book_list.paginator.page_range %}

        {% if book_list.number == page %}
            <a href="?page={{ page }}" class="btn btn-success">{{ page }}</a>
        {% else %}
            <a href="?page={{ page }}" class="btn btn-info">{{ page }}</a>
        {% endif %}

    {% endfor %}

    {% if book_list.has_next %}
        <a href="?page={{ book_list.next_page_number }}" class="btn btn-primary">Next</a>
    {% endif %}
{% endblock content %}

books/templates/book_update.html
{% extends 'base.html' %}
{% block title %}
    Update book
{% endblock title %}
{% block content %}
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <label for="title"><h4>Title</h4></label>
        <input type="text" name="title" value="{{ form.title }}"><br>

        <label for="author"><h4>Author</h4></label>
        <input type="text" name="author" value="{{ form.author }}"><br>

        <label for="picture"><h4>Picture</h4></label>
{#        <img src="{{ form.picture }}" alt="">#}
        <input type="file" name="picture" value=""><br>

        <label for="file"><h4>Picture</h4></label>
{#        <img src="{{ form.picture }}" alt="">#}
        <input type="file" name="file" value=""><br>

        <label for="count"><h4>Count</h4></label>
        <input type="number" name="count" value="{{ form.count }}"><br>

        <label for="cost"><h4>Cost</h4></label>
        <input type="number" name="cost" value="{{ form.cost }}"><br>

        <input type="submit" name="save" value="save">
    </form>
{% endblock content %}

books/templates/kartoteka_create.html
{% extends 'base.html' %}
{% block title %}
    create
{% endblock title %}

{% block content %}
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <table>
            <tr>
                {{ form }}
            </tr>
        </table>
        <input type="submit" class="btn btn-success" name="save" value="save">
    </form>
{% endblock content %}