Library_/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('', include('home.urls')),
                  path('admin/', admin.site.urls),
                  path('user/', include('users.urls')),
                  path('book/', include('books.urls')),
                  # path('email/', include('sendEmail.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

books/urls.py
from django.urls import path

from books.views import book_list, book_create, kartoteka_create, book_detail, book_category, book_update

app_name = 'books'
urlpatterns = [
    path('list/', book_list, name='book_list'),
    path('create/', book_create, name='book_create'),
    path('kartoteka_create/', kartoteka_create, name='kartoteka_create'),
    path('book_detail/<int:pk>', book_detail, name='book_detail'),
    path('category/<str:category>/', book_category, name='book_category'),
    path('book_update/<int:pk>/', book_update, name='book_update'),
]

home/urls.py
from django.urls import path

from home.views import home

app_name = 'home'

urlpatterns = [
    path('', home, name='home'),
]

users/urls.py
from django.urls import path

from .views import registration, _login, _logout, personal_cabinet, reset_password, verify_user, \
    user_update

app_name = 'users'
urlpatterns = [
    path('registration/', registration, name='registration'),
    path('login/', _login, name='_login'),
    path('logout/', _logout, name='logout'),
    path('personal_cab/', personal_cabinet, name='personal_cabinet'),
    path('reset_password/', reset_password, name='reset_password'),
    path('verify/', verify_user, name='verify_user'),
    path('update_user/', user_update, name='user_update'),
]

templates/base.html
<!DOCTYPE html>
{% load static %}
{% load my_tags %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}

        {% endblock title %}
    </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'home:home' %}">Home</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'books:book_list' %}">Books</a>
                    </li>
                    {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{% url 'users:personal_cabinet' %}">Cabinet</a>
                        </li>
                    {% endif %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                           data-bs-toggle="dropdown" aria-expanded="false">
                            Dropdown
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item"
                                   href="{% url 'books:book_category' 'Historical' %}">Historical</a></li>
                            <li><a class="dropdown-item"
                                   href="{% url 'books:book_category' 'Scientific' %}">Scientific</a></li>
                            <li><a class="dropdown-item" href="{% url 'books:book_category' 'For_Kids' %}">For Kids</a>
                            </li>
                            <li><a class="dropdown-item"
                                   href="{% url 'books:book_category' 'Literature' %}">Literature</a></li>
                        </ul>
                    </li>
                    {% if request.user|has_role:"Manager,Admin" %}
                        <li class="nav-item">
                            <a class="" href="{% url 'books:book_create' %}" tabindex="-1"
                               aria-disabled="true">{{ user.groups.first }}</a>
                        </li>
                    {% endif %}
                </ul>
                {% if user.is_authenticated %}

                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:logout' %}">Log out</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:_login' %}">Login</a>
                    </li>
                {% endif %}

                {% if user.is_authenticated %}
                    {% if user.is_staff %}
                        {% if user.employee.picture %}
                            <li class="nav-item">
                                <a href="{% url 'users:user_update' %}">
                                    <img src="{{ user.employee.picture.url }}" alt="" class="profile_pic"></a>
                            </li>
                            <li class="nav-item">
                                {{ user.username }}
                            </li>
                        {% endif %}
                    {% else %}
                        {% if user.reader.picture %}
                            <li class="nav-item">
                                <a href="{% url 'users:user_update' %}">
                                    <img src="{{ user.reader.picture.url }}" alt="" class="profile_pic"></a>
                            </li>
                            <li class="nav-item">
                                {{ user.username }}
                            </li>
                        {% endif %}
                    {% endif %}


                {% endif %}


                <form class="d-flex">
                    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search"
                           name="search" value="{{ request.GET.search }}">
                    <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
            </div>
        </div>
    </nav>
</head>
<body>
{% block content %}

{% endblock content %}

{% block footer %}

{% endblock footer %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
</body>
</html>